### ISSUE TITLE
What is best way to config import settings for sound and music?

### ISSUE THREAD

**Issue by takaaptech** [LightGive/SimpleSoundManager#2]
Hi, @LightGive I found this plugin so awesome, simple and very useful!
Could you please show me what is the best practice to organize and config import settings for sound effect (small file) and music (background music)
I want to learn how to import settings so the game can load fast and sounds are play smooth
Thank so much for creating this plugin!

**Comment by LightGive** [comment]
> Hi, @LightGive I found this plugin so awesome, simple and very useful!
> Could you please show me what is the best practice to organize and config import settings for sound effect (small file) and music (background music)
> I want to learn how to import settings so the game can load fast and sounds are play smooth
> Thank so much for creating this plugin!

To import the music file, just put the music file in "LightGive / Managers / SimpleSoundManager / Sounds / Bgm or Se" and check with the inspector. SoundName.cs will be changed automatically afterwards.

It is a movie to import new music files.
https://youtu.be/MtW4qAtpzIg

I do not know much of the detailed setting of the sound, so please use the "AudioMixer" etc. for the detailed setting and set by yourself.

Thank you very much for using me!
I will keep updating from now on.

Please let me know if you do not understand anything else.
I will answer as much as possible.

**Comment by takaaptech** [comment]
Hi @LightGive 
Thank so much for the quick answer!
Everything good until now. For the demo, I think you can add a slider for control volume total, button for on/off sound and button for on/ off music (Which is as I guess is biding with volumeTotal,volumeBgm,volumeSe). 
Thank you!

**Comment by LightGive** [comment]
surely!
Thank you for giving us adequate advice.

I think I will put it in tomorrow.
Thank you.
